// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnzhewphabuhcbinsekw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhuemhld3BoYWJ1aGNiaW5zZWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MzEyNDMsImV4cCI6MjA3NzEwNzI0M30.4dcKeYXLA8fTxC2pBZqN2lENBBMpPUkL9WOMMnrYrJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});